# Dependabot configuration for automated dependency updates
# Documentation: https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2

updates:
  # Rust dependencies (Cargo.toml/Cargo.lock)
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 10
    reviewers:
      - "jungamer-64"
    labels:
      - "dependencies"
      - "rust"
    commit-message:
      prefix: "deps(cargo)"
      include: "scope"
    # Security updates are applied immediately
    versioning-strategy: increase

  # GitHub Actions workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 5
    reviewers:
      - "jungamer-64"
    labels:
      - "dependencies"
      - "ci"
      - "github-actions"
    commit-message:
      prefix: "ci(deps)"
      include: "scope"
    # Pin to specific commit SHA for security
    # Dependabot will update both the SHA and the version comment

  # Docker base images (Dockerfile)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "11:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 3
    reviewers:
      - "jungamer-64"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "deps(docker)"
      include: "scope"
