repos:
  - repo: local
    hooks:
      - id: gitleaks-scan
        name: gitleaks detect
        entry: scripts/pre-commit-gitleaks.sh
        language: script
        pass_filenames: false
        stages: [commit]
        description: "Run gitleaks detect before committing to prevent accidental secrets"
