[package]
name = "cms-backend"
version = "1.0.0"
edition = "2021"

[lib]
name = "cms_backend"
path = "src/lib.rs"

[[bin]]
name = "cms-backend"
path = "src/main.rs"

[dependencies]
# Web Framework
axum = { version = "0.7", features = ["multipart"] }
tower = "0.4"
tower-http = { version = "0.5", features = ["cors", "trace", "fs"], default-features = false }
hyper = { version = "1.0", features = ["full"] }

# Async Runtime
tokio = { version = "1.35", features = ["full"] }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Database - PostgreSQL with Diesel
diesel = { version = "2.1", features = ["postgres", "uuid", "chrono", "serde_json", "r2d2"] }
diesel_migrations = "2.1"

# Search - Tantivy (Rust-native full-text search)
tantivy = "0.22"

# Authentication (without OpenSSL dependencies)
jsonwebtoken = "9.2"
bcrypt = "0.15"

# Utilities
uuid = { version = "1.7", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
anyhow = "1.0"
thiserror = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# Caching
redis = { version = "0.24", features = ["tokio-comp", "serde_json"] }

# Configuration
dotenv = "0.15"

# Validation
validator = { version = "0.18", features = ["derive"] }

# Media Processing
image = "0.24"
mime = "0.3"

# OpenAPI Documentation
utoipa = { version = "4.2", features = ["axum_extras", "chrono", "uuid"] }
utoipa-swagger-ui = { version = "6.0", features = ["axum"] }

# Additional utilities
base64 = "0.22"
url = "2.5"
percent-encoding = "2.3"
urlencoding = "2.1"
rand = "0.8"
