[package]
name = "cms-backend"
version = "1.0.0"
edition = "2021"

[lib]
name = "cms_backend"
path = "src/lib.rs"

[[bin]]
name = "cms-backend"
path = "src/main.rs"

[dependencies]
axum = { version = "0.7", features = ["multipart"] }
tower = "0.4"
tower-http = { version = "0.5", features = ["cors", "trace", "fs"], default-features = false }
hyper = { version = "1.0", features = ["full"] }

tokio = { version = "1.35", features = ["full"] }

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

diesel = { version = "2.1", features = ["postgres", "uuid", "chrono", "serde_json", "r2d2"] }
diesel_migrations = "2.1"

tantivy = "0.22"
jsonwebtoken = "9.2"
bcrypt = "0.15"

uuid = { version = "1.7", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
anyhow = "1.0"
thiserror = "1.0"
tracing = "0.1"

redis = { version = "0.24", features = ["tokio-comp", "serde_json"] }

[dependencies.optional]
# kept trimmed
