# Environment setting for the CMS
environment = "development"

[server]
host = "127.0.0.1"
port = 3000
max_request_size = 10485760
request_timeout = 30
worker_threads = 4

[media]
upload_dir = "./uploads"
max_file_size = 10485760
allowed_types = ["jpg","jpeg","png","gif","webp","pdf","txt","md"]
thumbnail_sizes = [[150, 150], [300, 300]]

[notifications]
[notifications.email]
smtp_host = "localhost"
smtp_port = 587
smtp_username = "user"
smtp_password = "${SMTP_PASSWORD}"
from_address = "noreply@example.com"
from_name = "CMS"

[notifications.webhooks]
enabled = false
timeout = 30
retry_attempts = 3

[security]
# CORS origins allowed for development
cors_origins = ["http://localhost:3000"]
# Rate limiting defaults
rate_limit_requests = 100
rate_limit_window = 60
enable_login_rate_limiting = true

[database]
# Use environment variable to avoid committing secrets. Set DATABASE_URL in your environment.
# Example: DATABASE_URL=postgresql://user:password@host:5432/dbname?sslmode=require
# If your password contains special characters, URL-encode them (e.g. ^ -> %5E, & -> %26).
url = "${DATABASE_URL}"
# Connection pool and timeouts
max_connections = 20
min_connections = 5
connection_timeout = 30
idle_timeout = 600
max_lifetime = 3600
enable_migrations = true

[auth]
# JWT settings (Phase 5.4.2)
jwt_secret = "${JWT_SECRET}"
# Biscuit settings
biscuit_root_key = "${BISCUIT_ROOT_KEY}"
# Password hashing
bcrypt_cost = 12
# Session and token TTLs (in seconds)
session_timeout = 86400
access_token_ttl_secs = 3600
refresh_token_ttl_secs = 86400
remember_me_access_ttl_secs = 86400
# Production environment flag (default: false for development)
is_production = false

[auth.webauthn]
rp_id = "localhost"
rp_name = "CMS"
rp_origin = "http://localhost:3000"
timeout = 60000
