name: Security Audit

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
  push:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
  schedule:
    - cron: '23 3 * * *'  # 毎日 03:23 UTC
  workflow_dispatch: {}

permissions:
  contents: read
  security-events: write

concurrency:
  group: security-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cargo-deny:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Cache cargo registry & index
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

      - name: Install cargo-deny
        run: cargo install cargo-deny --locked

      - name: Run cargo-deny (advisories/licenses)
        run: |
          cargo deny check advisories bans licenses sources sources --hide-inclusion-graph

  audit:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Cache cargo registry & index
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

      - name: Install cargo-audit
        run: cargo install cargo-audit --locked

      - name: cargo audit
        run: cargo audit --deny warnings --deny unsound --color always || true
        # 既知の一時的 CVE がある場合でも PR を止めないため一旦失敗を許容。将来ポリシーで厳格化。
